version: '3.8'

services:
  rust:
    build: .
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true
    # command: bash -c "cargo build --release && cargo run --release"
    # ports:
      # - 8000:8000