version: '3.8'

services:
  rust:
    build: .
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true
    ports:
      - 8000:8000
    # command: bash -c "cargo build --release && cargo run --release"
    